networks:
  default:
    name: test
    external: true
services:
  dbgate:
    image: dbgate/dbgate:6.4.1-alpine
    restart: always
    ports:
      - 80:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1,con2,con3,con4
      LABEL_con1: Sungate
      SERVER_con1: sungate-db
      USER_con1: sunhouse_sungate
      PASSWORD_con1: sungate@121
      PORT_con1: 3306

      ENGINE_con1: mysql@dbgate-plugin-mysql
      LABEL_con2: Postgres
      SERVER_con2: postgres
      USER_con2: postgres
      PASSWORD_con2: TEST
      PORT_con2: 5432
      ENGINE_con2: postgres@dbgate-plugin-postgres
      LABEL_con3: MongoDB
      URL_con3: mongodb://mongo:27017
      ENGINE_con3: mongo@dbgate-plugin-mongo
volumes:
  dbgate-data:
    driver: local
