version: "3.8"

services:
    laravel-app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        volumes:
            - /var/www/html/vendor
        depends_on:
            - postgres
        networks:
            - app-network
        ports:
            - "8000:80"

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
