version: "3.8"

services:
  app:
    container_name: tapeli.app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - .docker/apache/laravel.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password
    networks:
      - laravel

  db:
    container_name: tapeli.db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    container_name: tapeli.phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
