name: wordpress
services:
  wordpress:
    image: wordpress:6.7.2
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
  db-wordpress:
    image: mysql:latest
    container_name: db-wordpress
    environment:
      MYSQL_ROOT_PASSWORD: wppassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wppassword
    volumes:
      - ./mysql:/var/lib/mysql
