server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1000
    batchwait: 2s
    drop_rate_limited_batches: true

scrape_configs:
  - job_name: codeigniter_logs
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/www/html/app1/application/logs/log-*.php
          hostname: examplehostname
          app_name: app1

    pipeline_stages:
      - regex:
          expression: '^(?P<severity>ERROR|INFO|DEBUG|WARNING) - (?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) --> (?P<message>.*)$'
      - labels:
          severity:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
          location: Asia/Jakarta
      - tenant:
          value: default
      - match:
          selector: '{severity="INFO"}'
          stages:
            - drop:
                expression: "Helper loaded: .*"
            - drop:
                expression: "Language file loaded: .*"
            - drop:
                expression: "Controller Class Initialized"
            - drop:
                expression: "Model Class Initialized"
            - drop:
                expression: "Pagination Class Initialized"
            - drop:
                expression: "File loaded: .*"
            - drop:
                expression: "Final output sent to browser"
      - output:
          source: message
