networks:
  default:
    driver: bridge

services:
  minio:
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z-cpuv1
    container_name: minio
    environment:
      - MINIO_ROOT_USER=rentalizecdn
      - MINIO_ROOT_PASSWORD=rentalizeCDN@superSecret1945
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    restart: unless-stopped
    command: server --console-address ":9001" /data
    mem_limit: 125m
    cpus: 0.15
    networks:
      - default
