services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: <your_redis_password_here>
    volumes:
      - /home/ruangekspresidev/mounts/api/staging/neo-fipex/redis:/data
    networks:
      - default
